INSERT INTO scouts(first_name, last_name, rank, email, password, address, city, state, zip) VALUES ('Jason', 'Hamm', 'Star', 'jhamm.business@gmail.com', 'password', '190 Wetzel Lane', 'Brunswick', 'GA', '31523');
INSERT INTO scouts(first_name, last_name, rank, email, password, address, city, state, zip) VALUES ('Jack', 'Johson', 'Life', 'jack@johnson.com', 'password', '111 Main Street', 'Brunswick', 'GA', '31523');
INSERT INTO scouts(first_name, last_name, rank, email, password, address, city, state, zip) VALUES ('Eric', 'Clapton', 'Tenderfoot', 'eric@clapton.com', 'password', '333 Myers Hill Road', 'Brunswick', 'GA', '31523');
INSERT INTO scouts(first_name, last_name, rank, email, password, address, city, state, zip) VALUES ('Tristan', 'McGraw', 'Life', 'tristan@mcgraw.com', 'password', '444 South Port Boulevard', 'Brunswick', 'GA', '31523');
INSERT INTO scouts(first_name, last_name, rank, email, password, address, city, state, zip) VALUES ('Kaleck', 'Hamm', 'First Class', 'kaleck@hamm.com', 'password', '555 Buck Swamp Road', 'Brunswick', 'GA', '31523');

INSERT INTO advancements(name, eagle_required, type) VALUES
    ('Boy Scout', false, 'Rank'),
    ('Tenderfoot', false, 'Rank'),
    ('Second Class', false, 'Rank'),
    ('First Class', false, 'Rank'),
    ('Star', false, 'Rank'),
    ('Life', false, 'Rank'),
    ('Eagle', false, 'Rank');

INSERT INTO advancements(name, eagle_required, type) VALUES
    ('American Business', false, 'Merit Badge'),
    ('American Cultures', false, 'Merit Badge'),
    ('American Heritage', false, 'Merit Badge'),
    ('American Labor', false, 'Merit Badge'),
    ('Animal Science', false, 'Merit Badge'),
    ('Archaeology', false, 'Merit Badge'),
    ('Archery', false, 'Merit Badge'),
    ('Architecture', false, 'Merit Badge'),
    ('Art', false, 'Merit Badge'),
    ('Astronomy', false, 'Merit Badge'),
    ('Athletics', false, 'Merit Badge'),
    ('Automotive Maintenance', false, 'Merit Badge'),
    ('Aviation', false, 'Merit Badge'),
    ('Backpacking', false, 'Merit Badge'),
    ('Basketry', false, 'Merit Badge'),
    ('Bird Study', false, 'Merit Badge'),
    ('Bugling', false, 'Merit Badge'),
    ('Camping', true, 'Merit Badge'),
    ('Canoeing', false, 'Merit Badge'),
    ('Chemistry', false, 'Merit Badge'),
    ('Chess', false, 'Merit Badge'),
    ('Cinematography', false, 'Merit Badge'),
    ('Citizenship in the Community', true, 'Merit Badge'),
    ('Citizenship in the Nation', true, 'Merit Badge'),
    ('Citizenship in the World', true, 'Merit Badge'),
    ('Climbing', false, 'Merit Badge'),
    ('Coin Collecting', false, 'Merit Badge'),
    ('Collections', false, 'Merit Badge'),
    ('Communications', true, 'Merit Badge'),
    ('Composite Materials', false, 'Merit Badge'),
    ('Computers', false, 'Merit Badge'),
    ('Cooking', true, 'Merit Badge'),
    ('Crime Prevention', false, 'Merit Badge'),
    ('Cycling', true, 'Merit Badge'),
    ('Dentistry', false, 'Merit Badge'),
    ('Disabilities Awareness', false, 'Merit Badge'),
    ('Dog Care', false, 'Merit Badge'),
    ('Drafting', false, 'Merit Badge'),
    ('Electricity', false, 'Merit Badge'),
    ('Electronics', false, 'Merit Badge'),
    ('Emergency Preparedness', true, 'Merit Badge'),
    ('Energy', false, 'Merit Badge'),
    ('Engineering', false, 'Merit Badge'),
    ('Entrepreneurship', false, 'Merit Badge'),
    ('Environmental Science', true, 'Merit Badge'),
    ('Family Life', true, 'Merit Badge'),
    ('Farm Mechanics', false, 'Merit Badge'),
    ('Fingerprinting', false, 'Merit Badge'),
    ('Fire Safety', false, 'Merit Badge'),
    ('First Aid', true, 'Merit Badge'),
    ('Fish and Wildlife Management', false, 'Merit Badge'),
    ('Fishing', false, 'Merit Badge'),
    ('Fly Fishing', false, 'Merit Badge'),
    ('Forestry', false, 'Merit Badge'),
    ('Gardening', false, 'Merit Badge'),
    ('Game Design', false, 'Merit Badge'),
    ('Genealogy', false, 'Merit Badge'),
    ('Geocaching', false, 'Merit Badge'),
    ('Geology', false, 'Merit Badge'),
    ('Golf', false, 'Merit Badge'),
    ('Graphic Arts', false, 'Merit Badge'),
    ('Hiking', true, 'Merit Badge'),
    ('Home Repairs', false, 'Merit Badge'),
    ('Horsemanship', false, 'Merit Badge'),
    ('Indian Lore', false, 'Merit Badge'),
    ('Insect Study', false, 'Merit Badge'),
    ('Inventing', false, 'Merit Badge'),
    ('Journalism', false, 'Merit Badge'),
    ('Kayaking', false, 'Merit Badge'),
    ('Landscape Architecture', false, 'Merit Badge'),
    ('Law', false, 'Merit Badge'),
    ('Leatherwork', false, 'Merit Badge'),
    ('Lifesaving', true, 'Merit Badge'),
    ('Mammal Study', false, 'Merit Badge'),
    ('Medicine', false, 'Merit Badge'),
    ('Metalwork', false, 'Merit Badge'),
    ('Model Design and Building', false, 'Merit Badge'),
    ('Motorboating', false, 'Merit Badge'),
    ('Music', false, 'Merit Badge'),
    ('Nature', false, 'Merit Badge'),
    ('Nuclear Science', false, 'Merit Badge'),
    ('Oceanography', false, 'Merit Badge'),
    ('Orienteering', false, 'Merit Badge'),
    ('Painting', false, 'Merit Badge'),
    ('Personal Fitness', true, 'Merit Badge'),
    ('Personal Management', true, 'Merit Badge'),
    ('Pets', false, 'Merit Badge'),
    ('Photography', false, 'Merit Badge'),
    ('Pioneering', false, 'Merit Badge'),
    ('Plant Science', false, 'Merit Badge'),
    ('Plumbing', false, 'Merit Badge'),
    ('Pottery', false, 'Merit Badge'),
    ('Public Health', false, 'Merit Badge'),
    ('Programming', false, 'Merit Badge'),
    ('Public Speaking', false, 'Merit Badge'),
    ('Pulp and Paper', false, 'Merit Badge'),
    ('Radio', false, 'Merit Badge'),
    ('Railroading', false, 'Merit Badge'),
    ('Reading', false, 'Merit Badge'),
    ('Reptile and Amphibian Study', false, 'Merit Badge'),
    ('Rifle Shooting', false, 'Merit Badge'),
    ('Rowing', false, 'Merit Badge'),
    ('Robotics', false, 'Merit Badge'),
    ('Safety', false, 'Merit Badge'),
    ('Salesmanship', false, 'Merit Badge'),
    ('Scholarship', false, 'Merit Badge'),
    ('Scouting Heritage', false, 'Merit Badge'),
    ('Scuba diving', false, 'Merit Badge'),
    ('Sculpture', false, 'Merit Badge'),
    ('Search and Rescue', false, 'Merit Badge'),
    ('Shotgun Shooting', false, 'Merit Badge'),
    ('Skating', false, 'Merit Badge'),
    ('Small-Boat Sailing', false, 'Merit Badge'),
    ('Snow Sports', false, 'Merit Badge'),
    ('Soil and Water Conservation', false, 'Merit Badge'),
    ('Space Exploration', false, 'Merit Badge'),
    ('Sports', false, 'Merit Badge'),
    ('Stamp Collecting', false, 'Merit Badge'),
    ('Surveying', false, 'Merit Badge'),
    ('Sustainability', true, 'Merit Badge'),
    ('Swimming', true, 'Merit Badge'),
    ('Textile', false, 'Merit Badge'),
    ('Theater', false, 'Merit Badge'),
    ('Traffic Safety', false, 'Merit Badge'),
    ('Truck Transportation', false, 'Merit Badge'),
    ('Veterinary Medicine', false, 'Merit Badge'),
    ('Water Sports', false, 'Merit Badge'),
    ('Weather', false, 'Merit Badge'),
    ('Welding', false, 'Merit Badge'),
    ('Whitewater', false, 'Merit Badge'),
    ('Wilderness Survival', false, 'Merit Badge'),
    ('Wood Carving', false, 'Merit Badge'),
    ('Woodwork', false, 'Merit Badge');


INSERT INTO scout_advancements(scout_id, advancement_id) VALUES
    (1, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Boy Scout')),
    (1, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Tenderfoot')),
    (1, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Second Class')),
    (1, (SELECT advancements.id FROM advancements WHERE advancements.name = 'First Class')),
    (1, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Star')),
    (1, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Life')),
    (1, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Eagle'));

INSERT INTO scout_advancements(scout_id, advancement_id) VALUES
    (2, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Boy Scout')),
    (2, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Tenderfoot')),
    (2, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Second Class')),
    (2, (SELECT advancements.id FROM advancements WHERE advancements.name = 'First Class')),
    (2, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Star')),
    (2, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Life')),
    (2, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Eagle'));

INSERT INTO scout_advancements(scout_id, advancement_id) VALUES
    (3, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Boy Scout')),
    (3, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Tenderfoot')),
    (3, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Second Class')),
    (3, (SELECT advancements.id FROM advancements WHERE advancements.name = 'First Class')),
    (3, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Star')),
    (3, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Life')),
    (3, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Eagle'));

INSERT INTO scout_advancements(scout_id, advancement_id) VALUES
    (4, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Boy Scout')),
    (4, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Tenderfoot')),
    (4, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Second Class')),
    (4, (SELECT advancements.id FROM advancements WHERE advancements.name = 'First Class')),
    (4, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Star')),
    (4, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Life')),
    (4, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Eagle'));

INSERT INTO scout_advancements(scout_id, advancement_id) VALUES
    (5, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Boy Scout')),
    (5, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Tenderfoot')),
    (5, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Second Class')),
    (5, (SELECT advancements.id FROM advancements WHERE advancements.name = 'First Class')),
    (5, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Star')),
    (5, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Life')),
    (5, (SELECT advancements.id FROM advancements WHERE advancements.name = 'Eagle'));

-- Boy Scout
INSERT INTO requirements(description, internal_id) VALUES
    ('Meet the age requirements. Be a boy who is 11 years old, or one who has completed the fifth grade or earned the Arrow of Light Award and is at least 10 years old, but is not yet 18 years old.', 1),
    ('Find a Scout troop near your home.', 2),
    ('Complete a Boy Scout application and health history signed by your parent or guardian.', 3),
    ('Repeat the Pledge of Allegiance.', 4),
    ('Demonstrate the Scout sign, salute, and handshake.', 5),
    ('Demonstrate tying the square knot (a joining knot).', 6),
    ('Understand and agree to live by the Scout Oath, Scout Law, motto, slogan, and the Outdoor Code.', 7),
    ('Describe the Scout badge.', 8),
    ('Complete the pamphlet exercises. With your parent or guardian, complete the exercises in the pamphlet "How to Protect Your Children from Child Abuse: A Parent''s Guide".', 9),
    ('Participate in a Scoutmaster conference. Turn in your Boy Scout application and health history form signed by your parent or guardian, then participate in a Scoutmaster conference.', 10);

-- Tenderfoot
INSERT INTO requirements(description, internal_id) VALUES
    ('Present yourself to your leader, properly dressed, before going on an overnight camping trip. Show the camping gear you will use. Show the right way to pack and carry it.', 11),
    ('Spend at least one night on a patrol or troop campout. Sleep in a tent you have helped pitch.', 12),
    ('On the campout, assist in preparing and cooking one of your patrol''s meals. Tell why it is important for each patrol member to share in meal preparation and cleanup, and explain the importance of eating together.', 13),
    ('Do the following', 14),
    ('Demonstrate how to whip and fuse the ends of a rope.', 15),
    ('Demonstrate you know how to tie the following knots and tell what their uses are: two half hitches and the taut-line hitch.', 16),
    ('Using the EDGE method, teach another person how to tie the square knot.', 17),
    ('Explain the rules of safe hiking, both on the highway and cross-country, during the day and at night. Explain what to do if you are lost.', 18),
    ('Demonstrate how to display, raise, lower, and fold the American flag.', 19),
    ('Repeat from memory and explain in your own words the Scout Oath, Law, motto, and slogan.', 20),
    ('Know your patrol name, give the patrol yell, and describe your patrol flag.', 21),
    ('Explain the importance of the buddy system as it relates to your personal safety on outings and in your neighborhood. Describe what a bully is and how you should respond to one.', 22),
    ('Do the following.', 23),
    ('Record your best in the following tests:', 24),
    ('Current Results', 25),
    ('Push-ups', 26),
    ('Pull-ups', 27),
    ('Sit-ups', 28),
    ('Standing long jump', 29),
    ('1/4 mile walk/run', 30),
    ('30 days later', 31),
    ('Push-ups', 32),
    ('Pull-ups', 33),
    ('Sit-ups', 34),
    ('Standing long jump', 35),
    ('1/4 mile walk/run', 36),
    ('Show improvement in the activities listed in requirement 10a after practicing for 30 days.', 37),
    ('Identify local poisonous plants; tell how to treat for exposure to them.', 38),
    ('Do the following.', 39),
    ('Demonstrate how to care for someone who is choking.', 40),
    ('Show first aid for the following:', 41),
    ('Simple cuts and scrapes', 42),
    ('Blisters on the hand and foot', 43),
    ('Minor (thermal/heat) burns or scalds (superficial, or first degree)', 44),
    ('Bites or stings of insects and ticks', 45),
    ('Venomous snakebite', 46),
    ('Nosebleed', 47),
    ('Frostbite and sunburn', 48),
    ('Demonstrate Scout spirit by living the Scout Oath and Scout Law in your everyday life. Discuss four specific examples of how you have lived the points of the Scout Law in your daily life.', 49),
    ('Participate in a Scoutmaster conference.', 50),
    ('Complete your board of review.', 51);

-- 2nd Class
INSERT INTO requirements(description, internal_id) VALUES
    ('Do the following', 52),
    ('Demonstrate how a compass works and how to orient a map. Explain what map symbols mean.', 53),
    ('Using a compass and a map together, take a five-mile hike (or 10 miles by bike) approved by your adult leader and your parent or guardian.', 54),
    ('Discuss the principles of Leave No Trace.', 55),
    ('Do the following.', 56),
    ('Since joining, have participated in five separate troop/patrol activities (other than troop/patrol meetings), two of which included camping overnight.', 57),
    ('On one of these campouts, select your patrol site and sleep in a tent that you pitched. Explain what factors you should consider when choosing a patrol site and where to pitch a tent.', 58),
    ('Demonstrate proper care, sharpening, and use of the knife, saw, and ax, and describe when they should be used.', 59),
    ('Use the tools listed in requirement 3c to prepare tinder, kindling, and fuel for a cooking fire.', 60),
    ('Explain when it is appropriate to use a cooking fire. At an approved outdoor location and at an approved time, and using the tinder, kindling, and fuel wood from requirement 3d, demonstrate how to build a fire; light the fire, unless prohibited by local fire restrictions. After allowing the flames to burn safely for at least two minutes, safely extinguish the flames with minimal impact to the fire site.', 61),
    ('Explain when it is appropriate to use a lightweight stove or propane stove. Set up a lightweight stove or propane stove; light the stove, unless prohibited by local fire restrictions. Describe the safety procedures for using these types of stoves.', 62),
    ('On one campout, plan and cook one hot breakfast or lunch, selecting foods from the MyPlate food guide or the current USDA nutrition model. Explain the importance of good nutrition. Tell how to transport, store, and prepare the foods you selected.', 63),
    ('Participate in a flag ceremony for your school, religious institution, chartered organization, community, or troop activity. Explain to your leader what respect is due the flag of the United States.', 64),
    ('Participate in an approved (minimum of one hour) service project.', 65),
    ('Identify or show evidence of at least 10 kinds of wild animals (birds, mammals, reptiles, fish, mollusks) found in your community.', 66),
    ('Do the following.', 67),
    ('Show what to do for "hurry" cases of stopped breathing, serious bleeding, and ingested poisoning.', 68),
    ('Prepare a personal first aid kit to take with you on a hike.', 69),
    ('Demonstrate first aid for the following:', 70),
    ('Object in the eye', 71),
    ('Bite of a suspected rabid animal', 72),
    ('Puncture wounds from a splinter, nail, and fishhook', 73),
    ('Serious burns (partial thickness, or second-degree)', 74),
    ('Heat exhaustion', 75),
    ('Shock', 76),
    ('Heatstroke, dehydration, hypothermia, and hyperventilation', 77),
    ('Do the following.', 78),
    ('Tell what precautions must be taken for a safe swim.', 79),
    ('Demonstrate your ability to jump feetfirst into water over your head in depth, level off and swim 25 feet on the surface, stop, turn sharply, resume swimming, then return to your starting place.', 80),
    ('Demonstrate water rescue methods by reaching with your arm or leg, by reaching with a suitable object, and by throwing lines and objects. Explain why swimming rescues should not be attempted when a reaching or throwing rescue is possible, and explain why and how a rescue swimmer should avoid contact with the victim.', 81),
    ('Do the following.', 82),
    ('Participate in a school, community, or troop program on the dangers of using drugs, alcohol, and tobacco, and other practices that could be harmful to your health. Discuss your participation in the program with your family, and explain the dangers of substance addictions.', 83),
    ('Explain the three R''s of personal safety and protection.', 84),
    ('Earn an amount of money agreed upon by you and your parent, then save at least 50 percent of that money.', 85),
    ('Demonstrate Scout spirit by living the Scout Oath and Scout Law in your everyday life. Discuss four specific examples (different from those used for Tenderfoot requirement 13) of how you have lived the points of the Scout Law in your daily life.', 86),
    ('Participate in a Scoutmaster conference.', 87),
    ('Complete your board of review.', 88);

-- First Class
INSERT INTO requirements(description, internal_id) VALUES
    ('Demonstrate how to find directions during the day and at night without using a compass.', 89),
    ('Using a map and compass, complete an orienteering course that covers at least one mile and requires measuring the height and/or width of designated items (tree, tower, canyon, ditch, etc.)', 90),
    ('Since joining, have participated in 10 separate troop/patrol activities (other than troop/patrol meetings), three of which included camping overnight. Demonstrate the principles of Leave No Trace on these outings.', 91),
    ('Help plan a patrol menu for one campout that includes at least one breakfast, one lunch, and one dinner, and that requires cooking at least two of the meals. Tell how the menu includes the foods from the MyPlate food guide or the current USDA nutrition model and meets nutritional needs.', 92),
    ('Do the following:', 93),
    ('Using the menu planned in requirement 4a, make a list showing the cost and food amounts needed to feed three or more boys and secure the ingredients.', 94),
    ('Tell which pans, utensils, and other gear will be needed to cook and serve these meals.', 95),
    ('Explain the procedures to follow in the safe handling and storage of fresh meats, dairy products, eggs, vegetables, and other perishable food products. Tell how to properly dispose of camp garbage, cans, plastic containers, and other rubbish.', 96),
    ('On one campout, serve as your patrol''s cook. Supervise your assistant(s) in using a stove or building a cooking fire. Prepare the breakfast, lunch, and dinner planned in requirement 4a. Lead your patrol in saying grace at the meals and supervise cleanup.', 97),
    ('Visit and discuss with a selected individual approved by your leader (elected official, judge, attorney, civil servant, principal, teacher) your constitutional rights and obligations as a U.S. citizen.', 98),
    ('Identify or show evidence of at least 10 kinds of native plants found in your community.', 99),
    ('Do the following:', 100),
    ('Discuss when you should and should not use lashings. Then demonstrate tying the timber hitch and clove hitch and their use in square, shear, and diagonal lashings by joining two or more poles or staves together.', 101),
    ('Use lashing to make a useful camp gadget.', 102),
    ('Do the following:', 103),
    ('Demonstrate tying the bowline knot and describe several ways it can be used.', 104),
    ('Demonstrate bandages for a sprained ankle and for injuries on the head, the upper arm, and the collarbone.', 105),
    ('Show how to transport by yourself, and with one other person, a person:', 106),
    ('From a smoke-filled room', 107),
    ('With a sprained ankle, for at least 25 yards', 108),
    ('Tell the five most common signs of a heart attack. Explain the steps (procedures) in cardiopulmonary resuscitation (CPR).', 109),
    ('Do the following:', 110),
    ('Tell what precautions must be taken for a safe trip afloat.', 111),
    ('Successfully complete the BSA swimmer test.*', 112),
    ('With a helper and a practice victim, show a line rescue both as tender and as rescuer. (The practice victim should be approximately 31 feet from shore in deep water.)', 113),
    ('Tell someone who is eligible to join Boy Scouts, or an inactive Boy Scout, about your troop''s activities. Invite him to a troop outing, activity, service project, or meeting. Tell him how to join, or encourage the inactive Boy Scout to become active.', 114),
    ('Describe the three things you should avoid doing related to the use of the Internet. Describe a cyberbully and how you should respond to one.', 115),
    ('Demonstrate Scout spirit by living the Scout Oath and Scout Law in your everyday life. Discuss four specific examples (different from those used in Tenderfoot requirement 13 and Second Class requirement 11) of how you have lived the points of the Scout Law in your daily life.', 116),
    ('Participate in a Scoutmaster conference.', 117),
    ('Complete your board of review.', 118);

-- Star
INSERT INTO requirements(description, internal_id) VALUES
    ('Be active in your unit (and patrol if you are in one) for at least four months as a First Class Scout.', 119),
    ('Demonstrate Scout spirit by living the Scout Oath and Scout Law in your everyday life.', 120),
    ('Earn six merit badges, including any four from the required list for Eagle.', 121),
    ('While a First Class Scout, take part in service projects totaling at least six hours of work. These projects must be approved by your Scoutmaster.', 122),
    ('While a First Class Scout, serve actively in your unit for four months in one or more of the following positions of responsibility (or carry out a unit leader-assigned leadership project to help your unit):', 123),
    ('Take part in a Scoutmaster conference.', 124),
    ('Complete your board of review.', 125);

-- Life
INSERT INTO requirements(description, internal_id) VALUES
    ('Be active in your unit (and patrol if you are in one) for at least six months as a Star Scout.', 126),
    ('Demonstrate Scout spirit by living the Scout Oath and Scout Law in your everyday life.', 127),
    ('Earn five more merit badges (so that you have 11 in all), including any three more from the required list for Eagle.', 128),
    ('While a Star Scout, take part in service projects totaling at least six hours of work. These projects must be approved by your Scoutmaster.', 129),
    ('While a Star Scout, serve actively in your unit for six months in one or more of the positions of responsibility listed in requirement 5 for Star Scout (or carry out a Scoutmaster-assigned leadership project to help the troop).', 130),
    ('While a Star Scout, use the EDGE method to teach another Scout (preferably younger than you) the skills from ONE of the following seven choices, so that he is prepared to pass those requirements to his unit leader''s satisfaction.', 131),
    ('Second Class – 7a and 7c (first aid)', 132),
    ('Second Class – 1a (outdoor skills)', 133),
    ('Second Class – 3c, 3d, 3e, and 3f (cooking/camping)', 134),
    ('First Class – 8a, 8b, 8c, and 8d (first aid)', 135),
    ('First Class – 1, 7a, and 7b (outdoor skills)', 136),
    ('First Class – 4a, 4b, and 4d (cooking/camping)', 137),
    ('Three requirements from one of the required for Eagle merit badges, as approved by your unit leader.', 138),
    ('Take part in a Scoutmaster conference.', 139),
    ('Complete your board of review.', 140);

-- Eagle
INSERT INTO requirements(description, internal_id) VALUES
    ('Be active in your troop, team, crew, or ship for a period of at least six months after you have achieved the rank of Life Scout.', 141),
    ('Demonstrate that you live by the principles of the Scout Oath and Scout Law in your daily life. List on your Eagle Scout Rank Application the names of individuals who know you personally and would be willing to provide a recommendation on your behalf, including parents/guardians, religious, educational, and employer references.', 142),
    ('Earn a total of 21 merit badges (10 more than you already have), including the following:', 143),
    ('While a Life Scout, serve actively in your unit for a period of six months in one or more of the following positions of responsibility. List only those positions served after your Life board of review date.', 144),
    ('While a Life Scout, plan, develop, and give leadership to others in a service project helpful to any religious institution, any school, or your community. (The project should benefit an organization other than Boy Scouting.) The project proposal must be approved by the organization benefiting from the effort, your unit leader and unit committee, and the council or district before you start. You must use the Eagle Scout Leadership Service Project Workbook, BSA publication No. 521-927, in meeting this requirement. (To learn more about the Eagle Scout service project, see the Guide To Advancement, topics 9.0.2.0 through 9.0.2.15.)', 145),
    ('Take part in a unit leader conference.', 146),
    ('Successfully complete an Eagle Scout board of review. In preparation for your board of review, prepare and attach to your Eagle Scout Rank Application a statement of your ambitions and life purpose and a listing of positions held in your religious institution, school, camp, community, or other organizations, during which you demonstrated leadership skills. Include honors and awards received during this service.', 147);

-- Boy Scout
INSERT INTO advancement_requirements(advancement_id, requirement_id) VALUES
    ((SELECT id FROM advancements where name = 'Boy Scout'), 1 ),
    ((SELECT id FROM advancements where name = 'Boy Scout'), 2 ),
    ((SELECT id FROM advancements where name = 'Boy Scout'), 3 ),
    ((SELECT id FROM advancements where name = 'Boy Scout'), 4 ),
    ((SELECT id FROM advancements where name = 'Boy Scout'), 5 ),
    ((SELECT id FROM advancements where name = 'Boy Scout'), 6 ),
    ((SELECT id FROM advancements where name = 'Boy Scout'), 7 ),
    ((SELECT id FROM advancements where name = 'Boy Scout'), 8 ),
    ((SELECT id FROM advancements where name = 'Boy Scout'), 9 ),
    ((SELECT id FROM advancements where name = 'Boy Scout'), 10 );

-- Tenderfoot
INSERT INTO advancement_requirements(advancement_id, requirement_id) VALUES
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 11 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 12 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 13 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 14 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 15 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 16 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 17 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 18 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 19 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 20 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 21 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 22 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 23 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 24 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 25 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 26 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 27 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 28 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 29 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 30 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 31 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 32 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 33 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 34 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 35 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 36 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 37 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 38 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 39 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 40 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 41 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 42 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 43 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 44 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 45 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 46 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 47 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 48 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 49 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 50 ),
    ((SELECT id FROM advancements where name = 'Tenderfoot'), 51 );

-- 2nd Class
INSERT INTO advancement_requirements(advancement_id, requirement_id) VALUES
    ((SELECT id FROM advancements where name = 'Second Class'), 52 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 53 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 54 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 55 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 56 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 57 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 58 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 59 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 60 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 61 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 62 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 63 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 64 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 65 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 66 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 67 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 68 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 69 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 70 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 71 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 72 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 73 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 74 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 75 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 76 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 77 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 78 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 79 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 80 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 81 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 82 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 83 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 84 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 85 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 86 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 87 ),
    ((SELECT id FROM advancements where name = 'Second Class'), 88 );

-- First Class
INSERT INTO advancement_requirements(advancement_id, requirement_id) VALUES
    ((SELECT id FROM advancements where name = 'First Class'), 89 ),
    ((SELECT id FROM advancements where name = 'First Class'), 90 ),
    ((SELECT id FROM advancements where name = 'First Class'), 91 ),
    ((SELECT id FROM advancements where name = 'First Class'), 92 ),
    ((SELECT id FROM advancements where name = 'First Class'), 93 ),
    ((SELECT id FROM advancements where name = 'First Class'), 94 ),
    ((SELECT id FROM advancements where name = 'First Class'), 95 ),
    ((SELECT id FROM advancements where name = 'First Class'), 96 ),
    ((SELECT id FROM advancements where name = 'First Class'), 97 ),
    ((SELECT id FROM advancements where name = 'First Class'), 98 ),
    ((SELECT id FROM advancements where name = 'First Class'), 99 ),
    ((SELECT id FROM advancements where name = 'First Class'), 100 ),
    ((SELECT id FROM advancements where name = 'First Class'), 101 ),
    ((SELECT id FROM advancements where name = 'First Class'), 102 ),
    ((SELECT id FROM advancements where name = 'First Class'), 103 ),
    ((SELECT id FROM advancements where name = 'First Class'), 104 ),
    ((SELECT id FROM advancements where name = 'First Class'), 105 ),
    ((SELECT id FROM advancements where name = 'First Class'), 106 ),
    ((SELECT id FROM advancements where name = 'First Class'), 107 ),
    ((SELECT id FROM advancements where name = 'First Class'), 108 ),
    ((SELECT id FROM advancements where name = 'First Class'), 109 ),
    ((SELECT id FROM advancements where name = 'First Class'), 110 ),
    ((SELECT id FROM advancements where name = 'First Class'), 111 ),
    ((SELECT id FROM advancements where name = 'First Class'), 112 ),
    ((SELECT id FROM advancements where name = 'First Class'), 113 ),
    ((SELECT id FROM advancements where name = 'First Class'), 114 ),
    ((SELECT id FROM advancements where name = 'First Class'), 115 ),
    ((SELECT id FROM advancements where name = 'First Class'), 116 ),
    ((SELECT id FROM advancements where name = 'First Class'), 117 ),
    ((SELECT id FROM advancements where name = 'First Class'), 118 );

-- Star
INSERT INTO advancement_requirements(advancement_id, requirement_id) VALUES
    ((SELECT id FROM advancements where name = 'Star'), 119 ),
    ((SELECT id FROM advancements where name = 'Star'), 120 ),
    ((SELECT id FROM advancements where name = 'Star'), 121 ),
    ((SELECT id FROM advancements where name = 'Star'), 122 ),
    ((SELECT id FROM advancements where name = 'Star'), 123 ),
    ((SELECT id FROM advancements where name = 'Star'), 124 ),
    ((SELECT id FROM advancements where name = 'Star'), 125 );

-- Life
INSERT INTO advancement_requirements(advancement_id, requirement_id) VALUES
    ((SELECT id FROM advancements where name = 'Life'), 126 ),
    ((SELECT id FROM advancements where name = 'Life'), 127 ),
    ((SELECT id FROM advancements where name = 'Life'), 128 ),
    ((SELECT id FROM advancements where name = 'Life'), 129 ),
    ((SELECT id FROM advancements where name = 'Life'), 130 ),
    ((SELECT id FROM advancements where name = 'Life'), 131 ),
    ((SELECT id FROM advancements where name = 'Life'), 132 ),
    ((SELECT id FROM advancements where name = 'Life'), 133 ),
    ((SELECT id FROM advancements where name = 'Life'), 134 ),
    ((SELECT id FROM advancements where name = 'Life'), 135 ),
    ((SELECT id FROM advancements where name = 'Life'), 136 ),
    ((SELECT id FROM advancements where name = 'Life'), 137 ),
    ((SELECT id FROM advancements where name = 'Life'), 138 ),
    ((SELECT id FROM advancements where name = 'Life'), 139 ),
    ((SELECT id FROM advancements where name = 'Life'), 140 );

-- Eagle
INSERT INTO advancement_requirements(advancement_id, requirement_id) VALUES
    ((SELECT id FROM advancements where name = 'Eagle'), 141 ),
    ((SELECT id FROM advancements where name = 'Eagle'), 142 ),
    ((SELECT id FROM advancements where name = 'Eagle'), 143 ),
    ((SELECT id FROM advancements where name = 'Eagle'), 144 ),
    ((SELECT id FROM advancements where name = 'Eagle'), 145 ),
    ((SELECT id FROM advancements where name = 'Eagle'), 146 ),
    ((SELECT id FROM advancements where name = 'Eagle'), 147 );
