INSERT INTO scouts(firstName, lastName, rank, email, password, address, city, state, zip) VALUES ('Jason', 'Hamm', 'Star', 'jhamm.business@gmail.com', 'password', '190 Wetzel Lane', 'Brunswick', 'GA', '31523');
INSERT INTO scouts(firstName, lastName, rank, email, password, address, city, state, zip) VALUES ('Jack', 'Johson', 'Life', 'jack@johnson.com', 'password', '111 Main Street', 'Brunswick', 'GA', '31523');
INSERT INTO scouts(firstName, lastName, rank, email, password, address, city, state, zip) VALUES ('Eric', 'Clapton', 'Tenderfoot', 'eric@clapton.com', 'password', '333 Myers Hill Road', 'Brunswick', 'GA', '31523');
INSERT INTO scouts(firstName, lastName, rank, email, password, address, city, state, zip) VALUES ('Tristan', 'McGraw', 'Life', 'tristan@mcgraw.com', 'password', '444 South Port Boulevard', 'Brunswick', 'GA', '31523');
INSERT INTO scouts(firstName, lastName, rank, email, password, address, city, state, zip) VALUES ('Kaleck', 'Hamm', 'First Class', 'kaleck@hamm.com', 'password', '555 Buck Swamp Road', 'Brunswick', 'GA', '31523');

INSERT INTO advancements(name, eagle_required, type) VALUES
    ("American Business", false, 'Merit Badge'),
    ("American Cultures", false, 'Merit Badge'),
    ("American Heritage", false, 'Merit Badge'),
    ("American Labor", false, 'Merit Badge'),
    ("Animal Science", false, 'Merit Badge'),
    ("Archaeology", false, 'Merit Badge'),
    ("Archery", false, 'Merit Badge'),
    ("Architecture", false, 'Merit Badge'),
    ("Art", false, 'Merit Badge'),
    ("Astronomy", false, 'Merit Badge'),
    ("Athletics", false, 'Merit Badge'),
    ("Automotive Maintenance", false, 'Merit Badge'),
    ("Aviation", false, 'Merit Badge'),
    ("Backpacking", false, 'Merit Badge'),
    ("Basketry", false, 'Merit Badge'),
    ("Bird Study", false, 'Merit Badge'),
    ("Bugling", false, 'Merit Badge'),
    ("Camping", true, 'Merit Badge'),
    ("Canoeing", false, 'Merit Badge'),
    ("Chemistry", false, 'Merit Badge'),
    ("Chess", false, 'Merit Badge'),
    ("Cinematography", false, 'Merit Badge'),
    ("Citizenship in the Community", true, 'Merit Badge'),
    ("Citizenship in the Nation", true, 'Merit Badge'),
    ("Citizenship in the World", true, 'Merit Badge'),
    ("Climbing", false, 'Merit Badge'),
    ("Coin Collecting", false, 'Merit Badge'),
    ("Collections", false, 'Merit Badge'),
    ("Communications", true, 'Merit Badge'),
    ("Composite Materials", false, 'Merit Badge'),
    ("Computers", false, 'Merit Badge'),
    ("Cooking", true, 'Merit Badge'),
    ("Crime Prevention", false, 'Merit Badge'),
    ("Cycling", true, 'Merit Badge'),
    ("Dentistry", false, 'Merit Badge'),
    ("Disabilities Awareness", false, 'Merit Badge'),
    ("Dog Care", false, 'Merit Badge'),
    ("Drafting", false, 'Merit Badge'),
    ("Electricity", false, 'Merit Badge'),
    ("Electronics", false, 'Merit Badge'),
    ("Emergency Preparedness", true, 'Merit Badge'),
    ("Energy", false, 'Merit Badge'),
    ("Engineering", false, 'Merit Badge'),
    ("Entrepreneurship", false, 'Merit Badge'),
    ("Environmental Science", true, 'Merit Badge'),
    ("Family Life", true, 'Merit Badge'),
    ("Farm Mechanics", false, 'Merit Badge'),
    ("Fingerprinting", false, 'Merit Badge'),
    ("Fire Safety", false, 'Merit Badge'),
    ("First Aid", true, 'Merit Badge'),
    ("Fish and Wildlife Management", false, 'Merit Badge'),
    ("Fishing", false, 'Merit Badge'),
    ("Fly Fishing", false, 'Merit Badge'),
    ("Forestry", false, 'Merit Badge'),
    ("Gardening", false, 'Merit Badge'),
    ("Game Design", false, 'Merit Badge'),
    ("Genealogy", false, 'Merit Badge'),
    ("Geocaching", false, 'Merit Badge'),
    ("Geology", false, 'Merit Badge'),
    ("Golf", false, 'Merit Badge'),
    ("Graphic Arts", false, 'Merit Badge'),
    ("Hiking", true, 'Merit Badge'),
    ("Home Repairs", false, 'Merit Badge'),
    ("Horsemanship", false, 'Merit Badge'),
    ("Indian Lore", false, 'Merit Badge'),
    ("Insect Study", false, 'Merit Badge'),
    ("Inventing", false, 'Merit Badge'),
    ("Journalism", false, 'Merit Badge'),
    ("Kayaking", false, 'Merit Badge'),
    ("Landscape Architecture", false, 'Merit Badge'),
    ("Law", false, 'Merit Badge'),
    ("Leatherwork", false, 'Merit Badge'),
    ("Lifesaving", true, 'Merit Badge'),
    ("Mammal Study", false, 'Merit Badge'),
    ("Medicine", false, 'Merit Badge'),
    ("Metalwork", false, 'Merit Badge'),
    ("Model Design and Building", false, 'Merit Badge'),
    ("Motorboating", false, 'Merit Badge'),
    ("Music", false, 'Merit Badge'),
    ("Nature", false, 'Merit Badge'),
    ("Nuclear Science", false, 'Merit Badge'),
    ("Oceanography", false, 'Merit Badge'),
    ("Orienteering", false, 'Merit Badge'),
    ("Painting", false, 'Merit Badge'),
    ("Personal Fitness", true, 'Merit Badge'),
    ("Personal Management", true, 'Merit Badge'),
    ("Pets", false, 'Merit Badge'),
    ("Photography", false, 'Merit Badge'),
    ("Pioneering", false, 'Merit Badge'),
    ("Plant Science", false, 'Merit Badge'),
    ("Plumbing", false, 'Merit Badge'),
    ("Pottery", false, 'Merit Badge'),
    ("Public Health", false, 'Merit Badge'),
    ("Programming", false, 'Merit Badge'),
    ("Public Speaking", false, 'Merit Badge'),
    ("Pulp and Paper", false, 'Merit Badge'),
    ("Radio", false, 'Merit Badge'),
    ("Railroading", false, 'Merit Badge'),
    ("Reading", false, 'Merit Badge'),
    ("Reptile and Amphibian Study", false, 'Merit Badge'),
    ("Rifle Shooting", false, 'Merit Badge'),
    ("Rowing", false, 'Merit Badge'),
    ("Robotics", false, 'Merit Badge'),
    ("Safety", false, 'Merit Badge'),
    ("Salesmanship", false, 'Merit Badge'),
    ("Scholarship", false, 'Merit Badge'),
    ("Scouting Heritage", false, 'Merit Badge'),
    ("Scuba diving", false, 'Merit Badge'),
    ("Sculpture", false, 'Merit Badge'),
    ("Search and Rescue", false, 'Merit Badge'),
    ("Shotgun Shooting", false, 'Merit Badge'),
    ("Skating", false, 'Merit Badge'),
    ("Small-Boat Sailing", false, 'Merit Badge'),
    ("Snow Sports", false, 'Merit Badge'),
    ("Soil and Water Conservation", false, 'Merit Badge'),
    ("Space Exploration", false, 'Merit Badge'),
    ("Sports", false, 'Merit Badge'),
    ("Stamp Collecting", false, 'Merit Badge'),
    ("Surveying", false, 'Merit Badge'),
    ("Sustainability", true, 'Merit Badge'),
    ("Swimming", true, 'Merit Badge'),
    ("Textile", false, 'Merit Badge'),
    ("Theater", false, 'Merit Badge'),
    ("Traffic Safety", false, 'Merit Badge'),
    ("Truck Transportation", false, 'Merit Badge'),
    ("Veterinary Medicine", false, 'Merit Badge'),
    ("Water Sports", false, 'Merit Badge'),
    ("Weather", false, 'Merit Badge'),
    ("Welding", false, 'Merit Badge'),
    ("Whitewater", false, 'Merit Badge'),
    ("Wilderness Survival", false, 'Merit Badge'),
    ("Wood Carving", false, 'Merit Badge'),
    ("Woodwork", false, 'Merit Badge');

